export enum Type {
  PARAGRAPH = 'paragraph',
  H1 = 'heading-one',
  H2 = 'heading-two',
  H3 = 'heading-three',
  Ol = 'ol',
  Ul = 'ul',
  QUOTE = 'block-quote',
  ADVICE = 'advice',
  DIVIDER = 'divider',
  IMAGE = 'image',
  VIDEO = 'video',
  FILE = 'file',
  CODE = 'code',
  LIST_ITEM = 'list-item',
  LIST_ITEM_TEXT = 'list-item-text',
}
