name: Common Preparation Steps

on:
  workflow_call:
    outputs:
      xi_front_files:
        description: Will be 'true' xi.front's files have changed
        value: ${{ jobs.analyze_files.outputs.xi_front_files }}
      xi_frodo_files:
        description: Will be 'true' xi.frodo's files have changed
        value: ${{ jobs.analyze_files.outputs.xi_frodo_files }}

jobs:
  analyze_files:
    runs-on: ubuntu-latest

    outputs:
      xi_front_files: ${{ steps.path_filter.outputs.xi_front_files }}
      xi_frodo_files: ${{ steps.path_filter.outputs.xi_frodo_files }}
      lintable_files: ${{ steps.path_filter.outputs.lintable_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Filter paths
        uses: dorny/paths-filter@v2
        id: path_filter
        with:
          filters: .github/files.yml

  lint:
    runs-on: ubuntu-latest

    needs:
      - analyze_files

    if: needs.analyze_files.outputs.lintable_files == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        id: install
        run: npm install

      - name: Check format with prettier
        run: npm run format-check

      - name: Lint with ESLint
        if: success() || (failure() && steps.install.conclusion == 'success')
        run: npm run lint
