name: Common Preparation Steps

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: install
        name: Install dependencies
        run: npm install
      - name: Check format with prettier
        run: npm run format-check
      - name: Lint
        if: success() || (failure() && steps.install.conclusion == 'success')
        run: npm run lint
