name: Staging

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/common-prepare.yml

  build:
    needs: prepare
    uses: xi-effect/xieffect-actions/.github/workflows/docker-build.yml@main
    with:
      tag: front-staging
    secrets: inherit
