name: Development

on:
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/common-prepare.yml

  build:
    needs: prepare
    uses: xi-effect/xieffect-actions/.github/workflows/docker-build-nocache.yml@main
    with:
      tag: front-${{ github.run_id }}
    secrets: inherit
