name: Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/common-prepare.yml

  build:
    needs: prepare
    if: needs.prepare.outputs.xi_front_files == 'true'
    uses: xi-effect/xi.actions/.github/workflows/docker-build.yml@main
    with:
      tag: front-staging
      base-tag: front
    secrets: inherit

  build-frodo:
    needs: prepare
    if: needs.prepare.outputs.xi_frodo_files == 'true'
    uses: xi-effect/xi.actions/.github/workflows/docker-build.yml@main
    with:
      tag: frodo-staging
      base-tag: frodo
      target: builder
      arguments: "APP_NAME=xi.frodo"
    secrets: inherit
