name: Production Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/common-prepare.yml

  build-deploy:
    needs: prepare
    uses: xi-effect/xieffect-actions/.github/workflows/docker-full.yml@main
    with:
      tag: front
      images: front
    secrets: inherit
