name: Development

on:
  pull_request:
    branches:
      - staging
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/common-prepare.yml

  build:
    needs: prepare
    if: needs.prepare.outputs.xi_front_files == 'true'
    uses: xi-effect/xieffect-actions/.github/workflows/docker-build-nocache.yml@main
    with:
      tag: front-${{ github.run_id }}
    secrets: inherit

  build-frodo:
    needs: prepare
    if: needs.prepare.outputs.xi_frodo_files == 'true'
    uses: xi-effect/xieffect-actions/.github/workflows/docker-build-nocache.yml@main
    with:
      tag: frodo-${{ github.run_id }}
      target: builder
      arguments: "APP_NAME=xi.frodo"
    secrets: inherit
