name: Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    if: contains(fromJSON('["niqzart", "unknownproperty"]'), github.triggering_actor)
    uses: ./.github/workflows/common-prepare.yml

  build:
    needs: prepare
    if: >-
      contains(fromJSON('["niqzart", "unknownproperty"]'), github.triggering_actor)
      && needs.prepare.outputs.xi_front_files == 'true'

    uses: xi-effect/xi.actions/.github/workflows/docker-build.yml@main
    with:
      tag: front
    secrets: inherit

  deploy:
    needs: build
    if: >-
      contains(fromJSON('["niqzart", "unknownproperty"]'), github.triggering_actor)
      && needs.prepare.outputs.xi_front_files == 'true'

    runs-on: ubuntu-latest
    environment: xi-production

    steps:
      - name: Run SSH commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}
          script: |-
            cd ~/xieffect-core
            docker compose pull front
            docker compose up -d
            docker image prune -f
          script_stop: true

  build-frodo:
    needs: prepare
    if: >-
      contains(fromJSON('["niqzart", "unknownproperty"]'), github.triggering_actor)
      && needs.prepare.outputs.xi_frodo_files == 'true'

    uses: xi-effect/xi.actions/.github/workflows/docker-build.yml@main
    with:
      tag: frodo
      target: builder
      arguments: "APP_NAME=xi.frodo"
    secrets: inherit

  deploy-frodo:
    needs: build-frodo
    if: contains(fromJSON('["niqzart", "unknownproperty"]'), github.triggering_actor)

    runs-on: ubuntu-latest
    environment: xi-production

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract docs from the container
        uses: shrink/actions-docker-extract@v2
        id: extract
        with:
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_USERNAME }}:frodo
          path: /app/apps/xi.frodo/build/.

      - name: Push files via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}
          source: ${{ steps.extract.outputs.destination }}/*
          target: ~/xieffect-core/docusaurus/frodo/
          strip_components: 1
          rm: true
