name: Staging

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/common-prepare.yml

  build:
    needs: prepare
    if: needs.prepare.outputs.xi_front_files == 'true'
    uses: xi-effect/xieffect-actions/.github/workflows/docker-build.yml@main
    with:
      tag: front-staging
    secrets: inherit

  build-frodo:
    needs: prepare
    if: needs.prepare.outputs.xi_frodo_files == 'true'
    uses: xi-effect/xieffect-actions/.github/workflows/docker-build-nocache.yml@main
    with:
      tag: frodo-staging
      target: builder
      arguments: "APP_NAME=xi.frodo"
    secrets: inherit
